param(
    [ValidateSet('Debug','Release')]
    [string]$Config = 'Release',
    # -Publish: after build, assemble [dll + startup.cs + Config.ini + Helper.md] into a publish folder
    [switch]$Publish
)
$ErrorActionPreference = 'Stop'

# Build CFZOfflineMod and deploy to Mods\CFZOfflineMod\
# Load chain: UnityExplorer script (Mods\sinai-dev-UnityExplorer\Scripts\startup.cs) -> Assembly.LoadFrom -> CfzOffline.Boot.Run

$src      = Join-Path $PSScriptRoot 'cfz_mod.cs'
$root     = Split-Path $PSScriptRoot -Parent
$managed  = Join-Path $root 'CFWClient_Data\Managed'
$harmony  = Join-Path $root 'MelonLoader\net35\0Harmony.dll'
$modDir   = Join-Path $root 'Mods\CFZOfflineMod'
$outDll   = Join-Path $modDir 'CFZOfflineMod.dll'
$csc      = Join-Path $env:WINDIR 'Microsoft.NET\Framework64\v4.0.30319\csc.exe'
if (-not (Test-Path $csc)) { $csc = $csc -replace 'Framework64','Framework' }
if (-not (Test-Path $src))     { throw "source not found: $src" }
if (-not (Test-Path $managed)) { throw "game managed dir not found: $managed" }
if (-not (Test-Path $harmony)) { throw "0Harmony not found: $harmony" }

# ---- references: core + all UnityEngine modules (glob) ----
$refArgs = @('/nostdlib+',
             "/r:$(Join-Path $managed 'mscorlib.dll')",
             "/r:$(Join-Path $managed 'System.dll')",
             "/r:$(Join-Path $managed 'System.Core.dll')",
             "/r:$(Join-Path $managed 'Assembly-CSharp.dll')",
             "/r:$(Join-Path $managed 'PublisherModule.dll')",
             "/r:$(Join-Path $managed 'ProudDotNetClientUnity.dll')",
             "/r:$harmony",
             "/r:$(Join-Path $managed 'UnityEngine.dll')")
Get-ChildItem $managed -Filter 'UnityEngine.*.dll' | ForEach-Object { $refArgs += "/r:$($_.FullName)" }

# ---- compile ----
# Debug  : /define:DEBUG -> debug hotkeys(F1-F8/F11/F12/Shift+F10) + button probe + event observer + Latest.log
# Release: debug code stripped by #if DEBUG, only F9/F10 hotkeys remain
New-Item -ItemType Directory -Force -Path $modDir | Out-Null
$cscArgs = @('/nologo','/noconfig','/nowarn:0618,0649,0169,0414,0162',
             '/target:library','/platform:anycpu') + $refArgs
if ($Config -eq 'Debug') { $cscArgs += @('/define:DEBUG','/optimize-','/debug:full') }
else                     { $cscArgs += @('/optimize+') }
$cscArgs += @("/out:$outDll", $src)

& $csc $cscArgs
if ($LASTEXITCODE -ne 0) { throw "compile failed (exit $LASTEXITCODE)" }
Write-Host "build ok [$Config]: $outDll"

# ---- publish: dll + 3 resources (startup.cs / Config.ini / Helper.md) ----
if ($Publish) {
    $pubDir = Join-Path $PSScriptRoot 'publish\CFZOfflineMod'
    New-Item -ItemType Directory -Force -Path $pubDir | Out-Null
    Copy-Item $outDll $pubDir -Force
    Copy-Item (Join-Path $PSScriptRoot 'startup.cs') $pubDir -Force
    # Config.ini / Helper.md: prefer project copy, else the runtime-generated one (exists after first game run)
    foreach ($n in 'Config.ini','Helper.md') {
        $proj = Join-Path $PSScriptRoot $n
        $live = Join-Path $modDir $n
        if (Test-Path $proj)     { Copy-Item $proj $pubDir -Force; Write-Host "  + $n (project)" }
        elseif (Test-Path $live) { Copy-Item $live $pubDir -Force; Write-Host "  + $n (runtime-generated)" }
        else                     { Write-Host "  ! $n missing (generated by mod on first run), skipped" }
    }
    Write-Host ""
    Write-Host "publish folder: $pubDir"
    Get-ChildItem $pubDir | Select-Object Name,Length | Format-Table -AutoSize | Out-String
}
